### ISSUE TITLE
Typos and Additional Options

### ISSUE THREAD

**Issue by Mirrorman95** [K4YT3X/video2x#1]
In README.md, it says: "You can also change FOLDERIN and FOLDERIN if you want." Shouldn't one of those be FOLDEROUT or something?
Also, shouldn't there be an option to choose which video filtering process you want to use? Like using upconv_7_anime_style_art_rgb, upconv_7_photo, anime_style_art_rgb, photo, or anime_style_art_y instead of just photo? I guess I could edit the .py files to use the appropriate filter, but it would be easier if it was a command line option.
And if your graphics card supports cuDNN and you have support for it installed, can you use that option at the end by writing --cudnn instead of --gpu? I assume you can, but the readme did not specify that option.

**Comment by K4YT3X** [comment]
Sorry but I just see this post. Since this project is initialized during a hackathon, the quality of the code isn't that decent comparing to some of my other projects. I have already added the option to specify video filter and I will work on all the other suggested enhancements.

Thank you for your valuable suggestions.

(It might take a while since I have a number of ongoing projects.)

**Comment by K4YT3X** [comment]
Everything item this issue is resolved... I believe
