### ISSUE TITLE
Windows 10 GUI 0% CUDA usage

### ISSUE THREAD

**Issue by thesouljeff** [k4yt3x/video2x#1024]
First time testing the project and i´ve been testing several clips and drivers but i cannot find a way to get things moving more smoothly.

![SS1](https://github.com/k4yt3x/video2x/assets/57833058/1feb2e70-d8e5-41a2-819f-92edcee6affa)

This is my configuration during a running test (sorry for all being in Spanish) and even though this clip gets processed fairly quick when comparing others i was testing, i was hoping for this to be processed faster keeping in mind that i´m using a Quadro P5000.

I will continue to test out stuff but any insight is more than appreciated, i don´t want to smash my head to the desk for the following 5 days.

Cheers!

**Comment by ilkeroralkasim** [comment]
Did you try to modify the yaml  file, enter the GPU ID, from the screenshot 0 seems to be correct though.

**Comment by eyeEmotion** [comment]
First time user, I've got the same problem. There is not a lot activity going on with my GPU. A bit of the memory and bit of the 3D, nothing else (except for the CPU a bit too). Nothing on Cuda. And I know for certain Cuda is working for me, because I also use AI Depthmap generation and Cuda is always full.

I have a Nvidia RTX 3060 Dual OC v2.

It's only working at 0.05 fps. This would take forever.

@ilkeroralkasim : Where can I find the GPU ID and where in the yaml file should it be placed.
