### ISSUE TITLE
SRMD not using AMD RX 7800 XT GPU (Ubuntu 22.04 HWE, amdgpu 6.0.60002, Vulkan 1.3.275)

### ISSUE THREAD

**Issue by chucko58** [k4yt3x/video2x#1070]
I built video2x from source. The RealSR and RIFE algorithms are making good use of the GPU. But SRMD is using the CPU. I can see the CPU temperatures go up running SRMD, but the GPU temps stay close to idle. RealSR gets the GPU hot, and RIFE also makes good use of the GPU.

Everything works, and there are plenty of CPU cores, I'm just curious why I'm not seeing SRMD take advantage of the GPU.

Hardware: ASRock X570 Pro4 M, AMD Ryzen 9 5950X, Sapphire Pulse RX 7800 XT, 64 GB RAM.

Software: Ubuntu Studio 22.04, HWE kernel 6.5.0-17 (mainline 6.5.8), amdgpu 6.0.60002, vulkan 1.3.275, vulkan-amdgpu 23.40, Python 3.10.13.

**Comment by pfmacedo** [comment]
IMO the problem is likely the base image - looking at the docker file, it uses an Nvidia-provided image as the base (docker.io/nvidia/vulkan:1.3-470 ), which was last updated over two years ago and is based on an old Ubuntu release. A possible solution would be to change the Docker file to run a full dist upgrade to the current Ubuntu stable as one of the first steps and that might fix the issue.
