### ISSUE TITLE
Get progress from docker container

### ISSUE THREAD

**Issue by ks-zealot** [k4yt3x/video2x#1079]
Is there any way to get progress from upscaling process?
At least, get output in stdout and parse that.

**Comment by arximboldi** [comment]
I am having a similar issue. I only see the progress when I ctrl-c to quit. Is there a way to see the progress in real time or at least query it without quitting?

**Comment by arximboldi** [comment]
Ok, so the problem was that the docker images that are officially published are very old. Building an image from current `master` fixed the issue, mostly.

With `realsr`, there is still the problem that the output of the `realsr` process gets interleaved, that shows progress per frame, flooding the output. But otherwise it works rather well.
