### ISSUE TITLE
Command '['F:\\Summii Vfx\\Sumiii\\AE\\Samurai\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'F:\\Summii Vfx\\Sumiii\\AE\\Samurai\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '1:1:1', '-f', 'png', '-i', 'C:\\Users\\User\\AppData\\Local\\Temp\\video2x\\tmpkqy2jin7', '-o', 'C:\\Users\\User\\AppData\\Local\\Temp\\video2x\\tmp5q2k5e0u']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by Zeshyyy** [k4yt3x/video2x#1159]

**Comment by pu6karev** [comment]
I've got the same problem. 
I have an old video card, a GeForce 8800 GS. 
I changed the setting under "Main tab --> Express Setting --> Driver" from **Waifu2X NCNN Vulkan** to **Waifu2X Caffe**, 
and under "Driver Settings --> Process" from **gpu** to **cpu**, and the problem was solved.

You can try changing the same parameters as I did, or experiment with other available options in those sections.
