### ISSUE TITLE
6.0.0-beta.3 GUI: can't find realesrgan-plus param file

### ISSUE THREAD

**Issue by foolishgrunt** [k4yt3x/video2x#1184]
I get the following error whenever I try to run a process using realesrgan-plus:
![image](https://github.com/user-attachments/assets/95533acb-0095-4ea5-a1d0-62af791f9db4)
As you can see, it's looking for `realesrgan-plus-x2.bin`, but what's provided in the package `realesrgan-plus-x4.bin`

**Comment by k4yt3x** [comment]
I think that model just doesn't have that scaling ratio. This is to be expected. I'll make the UI more intuitive in the next releases.

**Comment by foolishgrunt** [comment]
I see, I was thinking that referred to a version number, not a scale factor. That makes sense now.

But speaking of more intuitive design, I have not been able to find documentation on what arguments are acceptable in the "Hardware Acceleration" field. What do I type to enable?
![image](https://github.com/user-attachments/assets/40f209e1-f260-4e64-a03c-eeb8adada03f)

**Comment by k4yt3x** [comment]
Basically all the values supported by FFMpeg, like vulkan, cuda, etc. It's NOT properly implemented now, since proper support of hardware accelerated decoding and stuff requires managing when frames are uploaded/downloaded from hardware. If you hover over it, you should see a tooltip saying it's still unstable. This will be properly implemented in the future.
