### ISSUE TITLE
system crashes on Ubuntu

### ISSUE THREAD

**Issue by padreputativo** [k4yt3x/video2x#1235]
The program consumes all the CPU, and the system crashes on Ubuntu. It seems that the memory used to create the frames is not being released, or it is waiting to have the entire video in memory before saving it, or something similar. It sounds like a memory leak issue.

**Comment by k4yt3x** [comment]
I don't think there are memory leaks in the current version. Could you provide more information about your system? How much RAM do you have, how much VRAM? What's your CPU and GPU model?

**Comment by padreputativo** [comment]
RAM 8GB
Swap 4GB
Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
Video RAM 4GB

When I click run, I see how the RAM keeps increasing without dropping at any point until it reaches the maximum, and Ubuntu stops all processes to recover in time, restarting the environment.

**Comment by k4yt3x** [comment]
Let me investigate deeper and I'll let you know.

**Comment by k4yt3x** [comment]
So I did some tests. I recall doing tests on this before, and here's the weird thing:

![image](https://github.com/user-attachments/assets/4ad6b211-9cf7-4c88-a36d-72cc36f29478)

It uses a LOT of ram (35.4G), which looks like a leak initially, but after some point the memory usage stabilizes and doesn't go any further. It stays the same for the rest of the processing of the video. Right now I'm not sure if it's actually a leak somewhere (neither valgrind nor heaptrack could find anything) or the encoder just wants that much RAM when the video output is 7680*4320. I'm kinda leaning towards the latter, since if it IS a leak then it won't look flat like this:

![image](https://github.com/user-attachments/assets/1b72714a-d31f-4fc9-9bcb-fb10ff523cb9)

**Comment by k4yt3x** [comment]
I tried libpacebo too, a flat line. I don't see any leaks:

![image](https://github.com/user-attachments/assets/d98e4013-033c-4db4-b9d1-aaeb721989e1)

I also don't see any infinite increase in memory use:

![image](https://github.com/user-attachments/assets/89f870f1-6817-45f7-97c9-b7e2a3395eb1)

With all said, **I currently don't believe there's a memleak. The program probably needs more RAM to process your video.** There's potentially room for improvement to use less RAM on systems with less memory, but it's not a leak.

**Comment by k4yt3x** [comment]
I did some more tests. It seems like you could adjust GOP size and encoder thread count to reduce the amount of RAM used. I'll make those adjustable. I think that's close to the most that I can do for now. I'll close the issue when those changes are pushed.

**Comment by padreputativo** [comment]
That would be great. It's likely that I don't have enough RAM and may never reach that "necessary" maximum "plateau." Handling so much data at such high resolution naturally requires a lot of RAM, but I suppose, as you mentioned, there must be a way to limit it so it can work on machines with just 8GB of RAM.

**Comment by k4yt3x** [comment]
Done. I added a lot more encoder options to make more room for optimizations (https://github.com/k4yt3x/video2x/commit/3215c898700cf1aaaa59ab8455a00ca88664a897). Of course, that along wouldn't be enough since you'll still need to know how to tweak it. I'd leave most of that to the community with professional knowledge in how FFmpeg works, but you could start with setting a lower thread count and lower GOP size.

Here's a preview. Updates in the GUI will come later:

![image](https://github.com/user-attachments/assets/333966ec-eb2a-4c1b-b1ce-e7a394924a5a)

This feature will be in the next release.

**Comment by padreputativo** [comment]
Many Thanks!
