### ISSUE TITLE
[Bug] FFmpeg Settings Container format seems to be ignored.

### ISSUE THREAD

**Issue by BoringName15** [k4yt3x/video2x#1239]
Steps to reproduce.

Drag an mp4 to the queue, change the container format to .mkv. Click start. The output file will have an mp4 container.
Drag an mkv to the queue, change the container format to .mp4. Click start. The output file will have an mkv container.

I tried setting the container format before and after dragging a file into the window but it made no difference.

It isn't just a wrong extension either. The actual containers are wrong. It's just exporting to the same container the source file is.

This is a great program. A hell of a lot faster than a python version I used a few years ago. And the results are spectacular in the few tests I've done. 

It would be good if it saved the ffmpeg settings.

**Comment by k4yt3x** [comment]
That's interesting, I'll investigate.

**Comment by k4yt3x** [comment]
You're absolutely right. I'll make a fix now.

**Comment by k4yt3x** [comment]
Done, it's been fixed in https://github.com/k4yt3x/video2x-qt6/commit/2932c2305f06daa7c9f944b4579e6f65cd21adda

I was being stupid and forgot I should get the suffix from the GUI and just used the input file's suffix.

![image](https://github.com/user-attachments/assets/b1abdc20-d080-410d-a3ac-a2511e4d0efb)

The fix will be in the next release.

**Comment by k4yt3x** [comment]
Oh and, thanks for the bug report.
