### ISSUE TITLE
Add Multithreading

### ISSUE THREAD

**Issue by wuast94** [K4YT3X/video2x#15]
Based on #11,

Enhance the overall performance with **multithreading**.

~~1. try to make waifu2x going to make multible pictures at once and not one by one.
https://github.com/K4YT3X/video2x/issues/11#issuecomment-431707841~~

~~1. Add a feature for adding folder within multiple files. 
https://github.com/K4YT3X/video2x/issues/11#issuecomment-431706764~~

**Comment by K4YT3X** [comment]
Hello @wuast94, thanks for opening a new issue. I already have the new version with multithreading ready last night. However, due to the GitHub outage (at least at my area), I wasn't able to interact with GitHub.

I have edited your issue, and here are the changes:

>1. try to make waifu2x going to make multible pictures at once and not one by one.
https://github.com/K4YT3X/video2x/issues/11#issuecomment-431707841

This statement is misleading. `video2x` is already telling waifu2x to process an entire folder of images at once. Unless there's something else that you mean, this has already been resolved in #11.

>1. Add a feature for adding folder within multiple files. 
https://github.com/K4YT3X/video2x/issues/11#issuecomment-431706764

This is a good idea, but that's not under the topic of adding mutithreading. Each feature should be in their own issue. Therefore, if you want that enhancement, please go ahead and open up a new issue. Thank you for your participation.

**Comment by K4YT3X** [comment]
@wuast94 ok I get you. Yeah that's multithreading. Starting version 2.1.0, video2x will create 5 waifu2x-caffe rendering threads by default. You can already try it out.

**Comment by wuast94** [comment]
Small test runs´s godd and i think fast too. bigger test is running now with 8 Threads

**Comment by wuast94** [comment]
Just a bit bad formatting but that are the smaller things :) 
![image](https://user-images.githubusercontent.com/16965460/47341545-8e489400-d6a1-11e8-935d-0d1d37c90c3e.png)

Now my Gpu is under 100% Compute in task manager. I think you got it .. good work :)

**Comment by K4YT3X** [comment]
@wuast94 I am aware of that problem. It's just when you have multiple threads printing on the same screen, the output stream conflicts. I'll add a thread lock like what I did to my konadl project. Should be an easy fix, doesn't even need an issue.

**Comment by K4YT3X** [comment]
The printing issue should also be fixed by now. I'll test it tonight.

**Comment by WSADKeysGaming** [comment]
Is the performance effect on multithreading measures? I was thinking of a
progress bar added back if the performance was similar before the progress
bar and multithreading.

**Comment by wuast94** [comment]
I can't test how much threads and performance I can get becouse my cpu is rip and I must ship it to dealer to repair it. But I think I can get more threads running :P

**Comment by K4YT3X** [comment]
@WSADKeysGaming we had a progress bar before, but that requires each image to be processed separately since waifu2x-caffe only outputs one line at the end no matter how many frames you upscale. However, upscaling each image individually really hurts the performance, as mentioned in #11 .
