### ISSUE TITLE
Settings File Paths Not Correct

### ISSUE THREAD

**Issue by up2urheadlights** [k4yt3x/video2x#172]
Cloned the repository and ran the setup python script.  Getting errors so I check the settings yaml and there are paths to c:/users/k4yt3x... and not my windows user name.  Also the settings assumes a java path to a specific jdk, and I have a different jre installed (for anime4k).  Note some of the paths are looking at my windows user name, so I think something in the setup script just isn't setting the correct paths for everything.  Would be nice if you ran the setup script and it found the correct path to JDK/JRE as well, but maybe ask the user for a path?  That or include a settings function in the GUI to set correct paths.

**Comment by k4yt3x** [comment]
You need exactly JDK 12 to be able to run Anime4K. Anything other than JDK 12 won't work. Therefore it's hard-coded.
If you do wish to try something else, the option is of course open to you. However, there's no plan to improve this at the moment, mainly due to the fact that I would very likely use a Python implementation of A4K, or at least recompile A4K with the newest JDK.

As for GUI, there will be more functions added to this in the form of GUI, but I'm really busy with my school stuff right now ant that has to wait.
