### ISSUE TITLE
Very very slow upscaling

### ISSUE THREAD

**Issue by adalvigi** [k4yt3x/video2x#204]
## Environment Information

I'm using the video2x-2.9.0-win32-full executable on Windows 8.1. I have an i7 4790 and a GTX 1060 3 GB.

I use the GUI and the following settings:
- Threads 8 (as my CPU has 4 core and hyperthreading)
- Method GPU
- Driver Waifu2X Caffe
- Preserve frames 1
- Image format PNG

## Symptom

I'm trying to upscale a 40 seconds video from 540x360 to 720x480. In like 6 hours it only did the 4% and my PC was heating a lot. I'm sorry if I come off as ignorant but I may have misunderstood what the required specs are, is this software supposed to run on a data center or something like that? I wonder what specs would you need to achieve the epic 360p to 4K anime upscales I see on the README if only an upscale from 360p to 480p takes so long...

Am I messing up the settings?

**Comment by k4yt3x** [comment]
First of all, your version (2.9.0) is obsolete. Old versions may contain major bugs or issues that are fixed in newer versions. I therefore strongly suggest you to use the newest version.

Before proceeding further, here are some suggestions to your current settings.

- Multithreading is not recommended for waifu2x, since one of my previous experiments discovered that hyperthreading waifu2x doesn't really give you much performance improvements. Leaving threads to 1 is recommended.
- If you set Preserve Frames to 1, then it will never delete the cache files, leaving you a lot of clutter on your disk. It has been set to 0 (False) by default in 2.10.0.

The next step I would take in this situation is to **open the Task Manager and observe the CUDA usage to see if waifu2x-caffe is actually using your GPU**. If you're not sure how to do it, refer to [this link](https://github.com/k4yt3x/video2x/wiki/Q&A#no-gpu-usage).

**Comment by adalvigi** [comment]
Thanks for the advice! The issue is that there's no full version for the 2.10.0 [on the release page](https://github.com/k4yt3x/video2x/releases) and I really don't want to mess around too much with dependencies on Windows. Would it be possible to have the full version of the 2.10.0 executable?

**Comment by k4yt3x** [comment]
I've been talking about a 3.0.0 full release, but I've yet got time to do it.
If you really want to get 2.10.0 working, just download the light version and run the setup script.
All the dependencies will be stored at `%LOCALAPPDATA%\video2x`, so if you want to delete all the clutter, there's only one folder to take care of.

I have no idea when I'll have time to make the new release, it will at least be after all the midterm stuff since I'm still a student.

**Comment by k4yt3x** [comment]
I just changed my mind. Just takes a bit working-hard to benefit many.
New release uploaded.
https://github.com/k4yt3x/video2x/releases/tag/3.0.0
