### ISSUE TITLE
libpng error: IDAT: CRC error QPixmap::scaled: Pixmap is a null pixmap

### ISSUE THREAD

**Issue by MatteCrystal** [k4yt3x/video2x#261]
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|4.2|
|`FFmpeg`|defualt|
|`waifu2x-caffe`|defualt|
|`waifu2x-converter-cpp`|defualt|
|`waifu2x-ncnn-vulkan`|defualt|

## Symptom

Continuation of issue #235 

Same basic report except I've upgraded to the latest 4.2 version and now I can see an error while processing the longer videos that crash my computer on the last merge step. Videos that complete successful don't seem to have these error messages. However, the crash doesn't happen untill after the up scaling process is finished.

## Screenshots or Error Messages
![image](https://user-images.githubusercontent.com/32424764/82464037-33e10680-9a83-11ea-9bce-99f65a493302.png)

```


```

**Comment by MatteCrystal** [comment]
Scratch that, I just successfully converted a video that was also showing these errors.

**Comment by zhanghai** [comment]
For anyone encountering this issue and was led here because it's the first result when searching for "video2x crc error": This is the GUI trying to show preview for the frame that's being upscaled, and if the GUI tried to read the frame before it's fully written to disk, it will print this error in console. Since it's just a GUI problem it should be safe to ignore. One can also verify this by disabling preview in GUI, and then this error should stop showing up.
