### ISSUE TITLE
Could there be a storage frendly mode

### ISSUE THREAD

**Issue by josh-65** [k4yt3x/video2x#265]
## Description
I'm trying to upscale low res videos but i don't have enough storage to store the extracted frames. I was thinking the could be a solution where it extracts 10 frames then scales them and then deletes the extracted frames and continues. Rather than it extracting all frames the scales all of them then delete the original extracted frames.

**Comment by sparkpedia** [comment]
Additionally for batch operations the cache does not clear itself after processing a video file. It would be nice to have an option to clear the cache before processing the next batch job as this kind of defeats the purpose of reading files from a folder.

**Comment by k4yt3x** [comment]
The cache folder should be cleared after each of the videos finish processing.
![image](https://user-images.githubusercontent.com/21986859/82846100-c3007b00-9ed6-11ea-9f8d-b7a5ae6f45ec.png)

**Comment by sparkpedia** [comment]
Sorry, I didnt see the v2.4.0 GUI release until now. Was this added in that release? I had changed the default cache location to be on a separate ssd to reduce ware on my boot disk and I am running Anime4kcpp though the cache files still persisted when I tried Waifu2x.

**Comment by k4yt3x** [comment]
@sparkpedia This is not a part of the GUI, but a part of the upscaler.
This functionality has always been there since almost a year ago.
However, the version back then had some bugs so processing multiple videos will cause the program to crash.
The only thing that has changed since then was the fixing of the said bug.
Please test to see if this work correctly. If it doesn't, I'll fix it.

**Comment by k4yt3x** [comment]
@josh-65 in order to do what you've just described, video2x will have to extract n frames, upscale n frames, and go back extracting more frames. This will require some major changes in the way how the program works currently. This might take some time.

At the mean time, you also have the option to slice the video into chunks if you're in a hurry.

**Comment by sparkpedia** [comment]
I did some tests with the latest Full release of the GUI and the cache files still persisted after the first file was finished processing. I tried running it again as administrator but the files still persisted. I am adding individual files in the GUI and outputting to a folder. I also let the GUI run through a couple files to see if it would remove the cache files after the full operation finished but it still didnt work.

**Comment by k4yt3x** [comment]
Really? Then there's a problem. I'll investigate this. Could you please open an new issue on this?

**Comment by Imsokray** [comment]
I suggest a different solution. Is there a way to point where the extracted frames can be stored? That way you could stick it to an external hard driver of 1 or 2TB. My system drive is SSD and 256 GB and the HDD data drive is 5 TB. Is there a way for the upscaler to store the extracted frames in the Data drive? I'm getting backed up really fast here.

**Comment by k4yt3x** [comment]
@Imsokray yes, you can set the temp directory in the config file. The key is at `video2x\video2x_cache_directory`.

**Comment by Imsokray** [comment]
Yes, I was away from PC so I couldn't respond, but figured out a way to move my TEMP and TMP folders to D, and am happily running a long footage now. 👍
