### ISSUE TITLE
Copy duplicated frames

### ISSUE THREAD

**Issue by Faniia** [k4yt3x/video2x#270]
## Description

I saw video2x read duplicated frames during extraction.
I thought it copied thoses frames instead of upscale each frame but it seems it does not.
In anime videos, there are lots of duplicated frames so it would be faster.

**Comment by k4yt3x** [comment]
There has been discussions around this in the discussion group. It's good to have an issue open so we can track this.
This is certainly possible, I'll just have to figure out exactly how to code this into v2x.

**Comment by koplo199** [comment]
Hi,
I tried to implement this feature, here is what I explored so far : 


**1°) Detecting duplicate frames by comparing them after frame extraction**

Not viable due to the O(n²) complexity of such algorithm

**2°) Detecting duplicate frames using hash algorithm like [ImageHash](https://pypi.org/project/ImageHash/) after frame extraction**

From my experience this is also not a viable solution, even by combining all different hash algorithm available in the lib to create a more 'unique' and longer hash, there is still too much false positive.

**3°) Using ffmpeg builtin [mpdecimate](https://ffmpeg.org/ffmpeg-filters.html#mpdecimate) feature**

This looks like the ideal solution, it is tunable via options and works really great. I've been using this method for the implementation.

Basically what the implementation does is relying on _ffmpeg_ to detect duplicate frames when extracting them. When using mpdecimate _ffmpeg_ will output bit-perfect duplicate _.png_ files, so we can hash them and using the hash as the key of a dictionary entry containing file names as values. After that, we only need to delete duplicate frames and restore them after upscaling.

This is not PR ready because I did not implemented a GUI option, only tested on Linux, and also not implemented a CLI option to disable it (but a change in the yaml file is sufficient not to use it).

If anyone wants to try it, here is the _.diff_ file :+1: 
[remove_duplicate.txt](https://github.com/k4yt3x/video2x/files/6759167/remove_duplicate.txt)

PS: I don't know if it's the same on Windows, but the _ffprobe_ step to retrieve the number of frames is really slow (nearly 15 minutes to finish on my i7 desktop cpu), I made a change to use _ffmpeg_ instead which terminates in seconds.

**Comment by k4yt3x** [comment]
Thanks for implementing this, but this will be available in 5.0, which I'm already working on.

**Comment by k4yt3x** [comment]
The newer version will use a frame server architecture, which will make it much easier to deduplicate frames. I'm currently implementing the frame interpolator. When that's done, I'll push it into the repo as a beta branch.

**Comment by koplo199** [comment]
@k4yt3x Sounds great ! Out of curiosity, how did you implement it ? Another problem I had was that because of video compression, identical frames were not bit-perfect copies, meaning that their hash could not be used to identify them. (Thus the need of mpdecimate.)

Also, is _ffprobe_ still used in 5.0 for getting the number of frames ? If so, do you think it would be possible to port my fix for using _ffmpeg_ instead ?

Thanks for your great work ! Getting frame interpolation would be awesome, I hope that project like [AnimeInterp](https://github.com/lisiyao21/AnimeInterp) will keep development ongoing, because other interpolation algorithms like RIFE did not give satisfying results when I tried them.

**Comment by k4yt3x** [comment]
> Out of curiosity, how did you implement it ?

Right now it's a TODO. What I was trying to say was that the images will now be PIL.Image objects, so it's possible to do `ImageChops.difference(image0, image1)`. Of course, as you said, this might not work perfectly, so more experiments are needed to come to a conclusion.

> Also, is ffprobe still used in 5.0 for getting the number of frames ?

No, I'm using OpenCV2 for that. I find it to be faster and easier.

>  ...but I hope that project like AnimeInterp will keep development ongoing, because other interpolation algorithms like RIFE did not give satisfying results when I tried them.

I agree. RIFE is not developed for anime-like videos. Right now I'm only adding support for *-ncnn-vulkan drivers in 5.0, but I'll look into the possibility of adding AnimeInterp in the future. It will be great if @nihui can make an ncnn + Vulkan implementation of it, which should significantly speed it up.

**Comment by koplo199** [comment]
Ok, looks like the architecture of 5.0 really is different than 4.x, I'll have a look after the beta branch is released.

Interestingly, I was also using OpenCV2 `absdiff()` in my first tests to compute the differences between two images, but gave up on the idea because comparing images to each other is too slow to be really useful : after all, what's the point of deleting duplicate frames if upscaling them is faster than detecting them ?

On a side note, I was using PIL `Image.tobytes()` at first to hash the image data, but it was also really slow : using `open()` and then `read()` made the duplication detection step to execute from 25 minutes, to 3 minutes (for more than 35 000 frames), I don't know yet if this optimization could be replicated elsewhere.

**Comment by k4yt3x** [comment]
@koplo199 5.0.0-beta is out. You can take a look at how I'm calculating it.

https://github.com/k4yt3x/video2x/blob/ac80de9399697f2f15e64845132a4d53a11efe1d/video2x/upscaler.py#L79-L85

**Comment by koplo199** [comment]
@k4yt3x Nice ! I'll probably have a look at it on my free time this weekend. I'm not familiar yet with `ImageChops.difference`, are you comparing each frames to each other or just consecutive ones ? That last method should be a lot faster (given the `O(n)` vs `O(n!)` complexity), and will probably give better results. 

But we may still have a problem even with that method : let's consider we set the threshold for duplicate frames at 96%, and that we have frame A which is 98% similar to frame B, which is itself 97% similar to frame C. With this method we'll  says that frames A, B and C are all duplicates, yet we know nothing about the similarity between frames A and C : it could be 90%, meaning we are far below the threshold, and that the end result would likely not being satisfying. This situation is likely to happens for scene with movements : each frame is almost similar to the previous one, but this difference becomes more and more significant as the number of frames grows.

I've no idea on how to solve this problem, maybe looking at how ffmpeg handle that issue in mpdecimate could help ?

**Comment by mirh** [comment]
https://github.com/n00mkrad/flowframes/blob/main/Code/Magick/Dedupe.cs
https://github.com/n00mkrad/flowframes/issues/8

**Comment by k4yt3x** [comment]
This is already supported. You can set it through `-t`, `--threshold`.
