### ISSUE TITLE
Trojan engine detected in scan from virus total.

### ISSUE THREAD

**Issue by Hedgy2** [k4yt3x/video2x#307]
## Description

Not sure on the legitmacy of the report but I am still concerned nonetheless, A scan of the main Video2x.exe on virustotal.com detected  a trojan engine in it (Trojan.Python.Agent).

## Sources

Paste links to descriptions of related documentations, websites and etc. here.
![image](https://user-images.githubusercontent.com/64325426/85210083-ff26d000-b30a-11ea-9966-5144c0fe47c4.png)

**Comment by TianZerL** [comment]
If you're worried about this, why not just [run it from code](https://github.com/K4YT3X/video2x/wiki/Run-From-Source-Code)?

**Comment by k4yt3x** [comment]
I have left this question unanswered for a few days because this question is actually more complex that it looks to answer properly. Below are some reasons why this is not a good indicator why the video2x.exe file is malicious.

1. As you can see, there's only one in 72 solutions that has marked this software malicious, and the only engine that has determined this file malicious is Ikarus, which is not a well-known engine like Symantec, Bitdefender or ESET. This, usually, means that the software is highly unlikely to be malicious. If you have multiple solutions marking a file suspicious, especially by popular well-trusted engines, then you might actually have a problem here. However, do note that some advanced FUD (fully undetected) malwares can achieve similar results as well, fooling most or even all engines, so it's good that you're being careful. In those cases, you'll have to take a look at PE file with disassemblers and debuggers like IDA Pro and x64dbg and dig into the code to understand if it's malicious or not.

1. The type of malware the engines mark the file as is important. In this case, the type of trojan Ikarus has marked the file as is "Python Agent". It is marking the file that will run a piece of Python code malicious presumably because it has now way of detecting if the Python code it will run is malicious or not. This, in my opinion, is both good and bad. Python code running within could be malicious, but by doing so it's also creating a lot of false positives like in this case. I am, for the most part, against just simply marking any PyInstaller-packaged files as malicious.

1. All Video2X releases are packaged by PyInstaller using the `Build.ps1` automation script. The script calls PyInstaller which then takes all the Python source code files and jams them into a PE (exe) file. The only possible source of contamination is from PyInstaller, which is unlikely to happen.

1. All Video2X releases come with file hashes, if you have verified the hashes carefully, then it's practically impossible that the file has been tampered with. Therefore no MITM attacks are possible if you're doing things correctly.

1. Last, and the most important part, I will never put undeclared malicious code into my software. You'll just have to trust the developers of the software you're using. If not, this is an open-source software. As what @TianZerL has suggested, you also have the freedom to just run from the source code, which you can read and audit to guarantee maliciousness-free.

**Comment by k4yt3x** [comment]
I hope the above response has cleared your concerns. If not, you're welcome to keep posting under this thread.
