### ISSUE TITLE
Few questions waifu2x Caffe

### ISSUE THREAD

**Issue by ageekhere** [k4yt3x/video2x#344]
Hi I have a few questions with video2x when using waifu2x Caffe
1. Does the waifu2x AI (that is trained) get updated? If so does it show when it was last updated?
2. Can video2x using waifu2x Caffe use more than 1 GPU for video processing? 
3. Can video2x output to HEVC H.265?

Thanks

**Comment by k4yt3x** [comment]
1. If you run from source then the setup script will always download the latest release of all components. If you use the release version then the latest components at the time it was packed will be included. You'll have to check the binaries to get the exact component version numbers.
1. Currently no. However since waifu2x-ncnn-vulkan recently added multi-GPU support, video2x will add support for multi-GPU some time in the future.
1. Yes. You'll have to change this to `libx265`.

![image](https://user-images.githubusercontent.com/21986859/91766884-c9377f00-ebca-11ea-85d9-da01400a91cc.png)

**Comment by ageekhere** [comment]
Cool thanks, side note do you know how often the ai is updated?

**Comment by k4yt3x** [comment]
Video2X supports a wide variety of backends or "drivers", namely `waifu2x_caffe`, `waifu2x_converter_cpp`, `waifu2x_ncnn_vulkan`, `srmd_ncnn_vulkan`, `realsr_ncnn_vulkan` and `anime4kcpp`.

Each of these drivers have its own developer(s) and thus its own development cycle. You'll have to check the upstream for your question to be answered.
