### ISSUE TITLE
Numerous libpng/QPixmap errors half way into upscaling

### ISSUE THREAD

**Issue by i0ntempest** [k4yt3x/video2x#371]
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.7.0
- **Upscaler version**:
- **GUI version**: 2.8.0
- **CLI version**:

## Symptom

Half way into upscaling i get numerous of: 
```
libpng error: Read Error
encode image C:\Users\SZF\AppData\Local\Temp\video2x\tmpx5r9pskj/extracted_4010.png failed
QPixmap::scaled: Pixmap is a null pixmap
```
And the output pictures are incomplete (half image and half black), or have a size of 0 bytes 

## Error Log or Screenshots
Using NCNN Vulkan:
![image](https://user-images.githubusercontent.com/16017904/94329367-701ff880-ff88-11ea-9aff-50e222db0423.png)

Using caffe:
![image](https://user-images.githubusercontent.com/16017904/94329353-4c5cb280-ff88-11ea-996b-0e18a7793772.png)

Log file, after I let it continue despite the spewing errors:
[video2x_error.log](https://github.com/k4yt3x/video2x/files/5286258/video2x_error.log)

**Comment by k4yt3x** [comment]
The `QPixmap` errors shouldn't be a problem. Someone posted a similar issue before but back then I didn't know what's causing this issue. After seeing this post I went back thinking about it and it might be due to the GUI trying to update the preview frame from a half-finished image. This error shouldn't be a worry. You can ignore it for now and I'll see if I can suppress the error message later.

From your error log it looks like waifu2x-caffe ran into a problem. However, since waifu2x-caffe didn't state what the problems is, I don't know what's wrong either. If it was able to process images previously, it might be a storage issue or some other changes that happened in the system which caused waifu2x-caffe to stop working.

**Comment by i0ntempest** [comment]
Seems it's kinda inconsistent. I tried again and both caffe and vulkan succeeded this time, with vulkan run gave a few QPixmap/libpng errors and caffe run gave none. Both AMD and NV driver got a minor update (yes I have 2 GPUs), not sure if this is related.

**Comment by k4yt3x** [comment]
QPixmap and libpng errors are safe to ignore as long as the upscale itself finishes successfully. The errors should only be induced by the image preview portion of the program, which will not cause the rest of the program to fault.

**Comment by k4yt3x** [comment]
Feel free to continue posting comments if you encounter more issues.
