### ISSUE TITLE
Support NVIDIA GPU Encoding (NVENC) for all steps that use ffmpeg

### ISSUE THREAD

**Issue by donicrosby** [k4yt3x/video2x#374]
## Description

Currently with the hwaccel being set to auto, even with a compatible GPU most of the processing is done on the CPU. This slows down the processing time considerably, being able to extract frames, remux video, and perform the final processing of the video on the GPU would reduce the time needed to convert videos.

I was tinkering with the configuration yaml and found an optimal solution for frame extraction 

There could be a follow on issue for support for AMD GPUs, but I haven't seen any documentation that shows what codecs or video options in ffmpeg are supported by MESA directly 

## Sources

https://ntown.at/de/knowledgebase/cuda-gpu-accelerated-h264-h265-hevc-video-encoding-with-ffmpeg/ (a little on the old side but still helpful)

**Comment by donicrosby** [comment]
Currently working on this
Should there be a checkbox under the General below Hardware Acceleration for CUDA GPU Acceleration?
I can put in the config.yaml under a nvidia_gpu section the needed options to swap out for frame extraction

Video Assembly will be a little tricky as the codec needs to be swapped, there's no -crf option so options would be:

- preset (set to slow for best bang for buck)
- tune (no animation just hq, ll, ull, lossless (hq probably should be default))
- rc(rate control) (set to cbr_hq)

I'm not sure if the UI should have an CUDA Output Options or they should also be in general

**Comment by donicrosby** [comment]
![image](https://user-images.githubusercontent.com/16298520/94744254-a8d41f00-0346-11eb-8b7f-ffe4dc43c074.png)

This is what I have so far

I also found a AMD version for the output codecs so as long as the needed settings are added to the GUI AMD and NVIDIA users should be able to quickly generate videos using their graphics cards rather than their CPUs

**Comment by k4yt3x** [comment]
Hardware encoding, to this date, is still "worse" than software encoding in general. Given the same bitrate, NVENC will have significantly more artifacts than software encoding, especially on older GPUs. Therefore, NVENC is not, and will not be the default in the foreseeable future. Given that the goal of this software is to enhance video quality, I will not suggest anyone to use hardware encoding either.

Right now, if you really want to use hardware encoding, you'll have to tune the settings manually. I will consider adding NVENC support for the GUI later, but it will not be a priority.

The design of the GUI also has to be reconsidered. The new options will merge into the existing options, instead of sitting a completely new group. Take `-vcodec` for example, it's a duplicating option. This option overlaps with the `-vcodec` option above, and is only triggered if CUDA hardware acceleration is checked. Instead of doing this, the more elegant way, in my opinion, will be to set a hook on the `-vcodec` LineEdit, and update the content of the ComboBox dynamically according to the options available to that codec. Vice versa for the rest of the options.

**Comment by donicrosby** [comment]
That's fine I can update the GUI to do that, I didn't want to cause any backwards compatibility problems. If you want the GUI to key off that fact that it has `nvenc` or `amf` in the codec and update all of the output options dynamically I can update it to do that.

That's why I posted the screen shot, just to make sure that I was going in the right direction. I want to give people like me who don't want the absolute best quality to still be able to use this to upscale videos quicker using their GPU to do the video encoding. But I don't want to clobber the GUI for everyone else just to be able to do what I want.

**Comment by k4yt3x** [comment]
Sorry for not replying for so long. I've been busy with school work and other projects. Feel free to develop a conceptual work if you're willing to. This will be of great help.
Please make sure that you're following the overall style and naming conventions though.

**Comment by semmyenator** [comment]
Is it possible to add -c:v hevc_amf to FFmpeg use the hardware processing of AMD GPU?
command example : "ffmpeg -i "input.mkv" -c:v hevc_amf -c:a copy output.mp4"

**Comment by donicrosby** [comment]
Yes my current fork automatically will switch the interface if you use AMF based h264/265. It gives you access to the similar options that NVEC would have.

I need to do some more testing of the interface this weekend to make sure it's rock solid and I'll make a pull request.

**Comment by k4yt3x** [comment]
@donicrosby sounds amazing. I'm thrilled to see the first GUI PR from the community.
I'm in the midterm week(s) right now, so it might still be a while before I can review your PR. Take your time.

**Comment by cfouche3005** [comment]
I wanted to test some nvenc encode but I didn't know what I have to change in yaml file.
