### ISSUE TITLE
FFmpeg or FFprobe cannot be found under the specified path

### ISSUE THREAD

**Issue by Jaswanth-spidey** [k4yt3x/video2x#437]
After all of the installation, I did the following Step by Step Tutorial[https://github.com/k4yt3x/video2x/wiki/Step-By-Step-Tutorial](url) @k4yt3x Please try to provide a solution ASAP!  I am providing my logcat of cp 

```
[+] INFO: Loading files into processing queue
2020-12-24 01:00:30.190105 [+] INFO: Input path(s): C:\Users\Jaswanth\Downloads\main_intro.mp4
2020-12-24 01:00:30.199196 [+] INFO: File MIME type: video/mp4`
`[!] ERROR: FFmpeg or FFprobe cannot be found under the specified path`
`[!] ERROR: Please check the configuration file settings`
`Traceback (most recent call last):
  File "C:\Users\Jaswanth\Desktop\Video2x\video2x-master\video2x-master\src\video2x_gui.py", line 105, in run
    self.fn(*self.args, **self.kwargs)
  File "C:\Users\Jaswanth\Desktop\Video2x\video2x-master\video2x-master\src\upscaler.py", line 633, in run
    self._check_arguments()
  File "C:\Users\Jaswanth\Desktop\Video2x\video2x-master\video2x-master\src\upscaler.py", line 281, in _check_arguments
    raise FileNotFoundError(self.ffmpeg_settings["ffmpeg_path"])`
`FileNotFoundError: C:\Users\Jaswanth\Desktop\Video2x\video2x-master\video2x-master\src\wrappers\ffmpeg.py
```

https://user-images.githubusercontent.com/62865929/103032166-6a38b400-4585-11eb-84ce-3d1580d2112d.mp4

This is the video I was upscaling "for your reference". I was trying to upscale this video to 1080p.

**Comment by k4yt3x** [comment]
What did you set the path to?
Also, it might be easier for you to just use the setup script.

**Comment by Demicro** [comment]
The location of the binaries should be automatically detected in the dependencies folder by default. Instead of being in a bad location like appdata @k4yt3x

**Comment by k4yt3x** [comment]
@Demicro the full released version does what you said -- looking for dependencies in the dependencies directory under the containing directory. The setup script coheres to the config which comes with the source code.

"Bad" here is subjective. Lots of programs install their binaries into `C:\Program Files` by default, not the desktop. Similarly, the setup script installs the dependencies into `%APPDATA%` because it's a standard place for applications to store static non-temp data. If you want to make it possible for the script to install dependencies in other directories via an argument, please open a new issue. The setup script wasn't supposed to be bulky. Like the Ubuntu setup script, it's only supposed to provide a standard easy-install. If you want to use v2x the easy way, use the release. If you're using the source, you should know what you're doing.

**Comment by Demicro** [comment]
@k4yt3x Thanks for answering. I realized after writing. I had replaced the binaries with the nightly version and that changed the path. What I did was change the configuration file with the full version keeping the binaries of the development version and thus have the correct location again.
