### ISSUE TITLE
[Feature Request] show frame extraction progress.

### ISSUE THREAD

**Issue by quicktus** [k4yt3x/video2x#464]
Some sort of indicator that it is (still) extracting frames and maybe its progress would be nice. 
As a noob I was worried it had crashed (20min+). It just takes some time for large videos (~130k 720p frames).
If you are worried it crashed while extracting frames (stuck on `INFO: Main process waiting for subprocesses to exit`), you can look at the size of the folder storing the extracted frames increasing.

**Comment by k4yt3x** [comment]
I wanted to add that, but I haven't been successful finding a way to poll the progress from FFmpeg elegantly...
I'll be appreciated if anyone can hint me on how that can be done.

**Comment by MailYouLater** [comment]
What about using [ffpb](https://pypi.org/project/ffpb/)?  Or if that's not an option, maybe take a look at the MIT licensed [ffpb source](https://github.com/althonos/ffpb) to see what it does to be able to show ffmpeg progress?

**Comment by k4yt3x** [comment]
@MailYouLater Hmmm that might actually be doable. I'm refactoring a large portion of this project's code right now. Invocation of FFmpeg is now done through ffmpeg-python. I'll see if that will work with ffpb. I think it might.

**Comment by k4yt3x** [comment]
![image](https://user-images.githubusercontent.com/21986859/120907353-a12fed00-c62e-11eb-8d1e-051cf1a11b78.png)

And I think it does work.

**Comment by MailYouLater** [comment]
I just came back after playing around with pointing the ffmpeg wrapper to ffpb instead of ffmpeg in version 4.8.1, and it operated, but didn't show the actual output.  I'm guessing somewhere you have it hiding/redirecting ffmpeg output, but I didn't see where.  Not much point in me continuing to bother with it though.  I don't know what I'm doing, and it looks like you've already got it up and running.  So I'll just look forward to future versions including this. 😄👍

**Comment by k4yt3x** [comment]
Yeah I redirected the Fmpeg process's stderr to the log file so it can be saved and uploaded whenever there's an error. Unfortunately due to how the logger works (you can only have one file descriptor), I can only write either to console or the file, so you won't see it in the console.

**Comment by kelvinnkat** [comment]
Is it possible to do something similar on the final video output section? For my project it seems to take over an hour for that step and I tend to quit the process since I have other things I'd like to do on my computer, but if I could at least know if the application is still running properly and how far is left to go that'd be nice.

**Comment by k4yt3x** [comment]
@kelvinnkat the whole program has been completely redesigned in version 5.0. You'll no longer have this problem when that rolls out.

**Comment by k4yt3x** [comment]
Both me and our other dev are students right now, so we can pretty much only work on this when we are on a break. The other dev will be done with school next month I believe. He'll be able to finish up some critical pieces in the project's dependency tree. When that's done, the new CLI version will be released. I'm not quite sure how long that'll take, but a fair estimation will be within Oct.

**Comment by k4yt3x** [comment]
This issue will no longer be a problem in 5.0.0.
