### ISSUE TITLE
Small fix regarding documentation for waifu2x model selection

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#49]
With some of the recent updates surrounding the new json config layout and the waifu2x model selection, the existing known usage of the command line `-y` option is out of date. If you use, for example `-y cunet` on the command line which used to work just fine, it now passes this as `--model_dir cunet` to waifu2x which is the wrong syntax it is expecting and thus fails that stage of the script.

I only noticed this as I had left the `-y` option in my batch file and it began failing once it got to the upscaling stage. It obviously functions fine if `-y` is dropped off and left to use the `model_dir` directive in the json file.

**Comment by K4YT3X** [comment]
Regarding this issue, I've just realized that `waifu2x-caffe` and `waifu2x-converter-cpp` have different types of models available, and their model selection is more complicated than I thought. You'll have to specify `--model_dir [directory containing the model files]` to select, instead of just `-y model`.

I'll look into this problem.

**Comment by cr08** [comment]
Got it. Just to clarify I use the caffe version as I have an Nvidia GPU. Haven't even looked at the CPP version. I've simply adjusted my batch file to remove the `-y` option and let the model_dir directive in the json file do the work.

**Comment by K4YT3X** [comment]
@cr08 I pushed a new update. This problem should be solved now.
