### ISSUE TITLE
2 questions, cache location, frame upscale size

### ISSUE THREAD

**Issue by Rmdhn1** [k4yt3x/video2x#533]
So, question, how do i change cache location? i'm on linux and installed this via AUR, secondly, when using RealSR, i had to abandon it because 1, it's 60 hours, 2, each frame is 8MB, 43000 frames is 300 something gigabyte, when i check the cache it renders AT 1440P, when i set it to 720p. now when it's finished it's probably gonna be 720p, but is there a way for the rendering to be 720p instead so it takes less time and space

**Comment by k4yt3x** [comment]
I've actually got no idea it's in the AUR. I was actually thinking about bring it into the AUR when 5.0.0 is stable.

---

In 4.0.0, the cache directory location can be changed in the configuration file (`video2x.yaml`).

![image](https://user-images.githubusercontent.com/21986859/128440614-df5fc84b-b2bb-4c68-b0fc-5fd3f579a1b7.png)

---

Version 5.0.0 will use a stream server model so there won't be all those intermediate frames that take up so much space.

RealSR has a fixed 4x upscaling ratio. There's no changing that unless you train the models yourself. If you set 2x instead of 4x, Video2X will simply upscale it by 4x then downscale with Lanczos back to 2x. It may actually take a bit longer since each frame will also have to go through a round of Lanczos. (This caveat will be documented after 5.0.0 is done.)

Yes I know it's kinda inflexible when you look at the implementation details.

**Comment by Rmdhn1** [comment]
alright, thanks atleast it wont hog up 80 gb of ssd space, also thank you very much for replying quickly

**Comment by Rmdhn1** [comment]
wait hold on, i think there's a way of going around it, it upscaled 4x yea? when i inputted 1080p as the settings IT'S RENDERING AT 7680 X 4320!!, AND WHEN I PUT 720P IT'S 1440P!, I think you should use this, if the input is 1080p, render it at 480p or something, RealSR then gives out 1080p images you don't need to scale wit Lancoz

**Comment by Rmdhn1** [comment]
why was it rendering at 1440p before and now at an insanely high resolution

**Comment by Rmdhn1** [comment]
nvm, when i cut the footage it became 1080p
