### ISSUE TITLE
Cleaning up cache directory

### ISSUE THREAD

**Issue by ser59** [k4yt3x/video2x#571]
Cleaning up cache directory

**Comment by k4yt3x** [comment]
Hello, I just want to add a note to this issue since we talked on Telegram and got your files recovered.

Currently, this behavior can be found explained in two places, the configuration file:

https://github.com/k4yt3x/video2x/blob/37d567f20833affd0552fd1797e7593563e70eef/src/video2x.yaml#L180

and the tooltip for the `Preserve Frames` checkbox:

https://github.com/k4yt3x/video2x/blob/37d567f20833affd0552fd1797e7593563e70eef/src/video2x_gui.ui#L566

Since this behavior might not be obvious enough, to avoid other users from running into this issue, a warning has been added to the latest release's download page to warn users about this possible confusing behavior. This behavior will be made more clear in the next release of the software.

I sincerely apologize for the inconveniences.
