### ISSUE TITLE
Do not support the decimals for upscaled factor?

### ISSUE THREAD

**Issue by pokedo0** [K4YT3X/video2x#6]
Do not support the decimals for upscaled factor?

**Comment by pokedo0** [comment]
in the meantime, there is some problem occuring as merging the pics to video.
![Imgur](https://i.imgur.com/V0QUPvV.png)
![Imgur](https://i.imgur.com/MWrX8E3.png)
However, i successfully get the upscaled video at last.

**Comment by K4YT3X** [comment]
Thank you for your issue!

The issue seems to me is that it's failing to merge the audio with the finished video. I am aware of that issue and I have been experimenting with it to see if I can solve it. If you check the destination that you specified for audio output, you should see a video file. If not, let me know.

The upscale factor doesn't support a decimal. I'm still hesitating whether to use a factor number or just use a target resolution (e.g. 1920x1080) as waifu2x wants the parameter to be. (or both?)

I will look into the issues and give you another response ASAP. Sorry if my fixes are delayed since I'm fairly busy recently :P

**Comment by pokedo0** [comment]
the audio seems crashed and the video track is ok.
the factor supports decimals for the offical waifu2x cafee, right?

**Comment by K4YT3X** [comment]
The audio issue didn't exist when I first developed this script. I will have it fixed.
Waifu2x caffe, I think, only supports the [length]x[height] format, but I'll double check that.

**Comment by pokedo0** [comment]
All problem have been solved. Thx~

**Comment by K4YT3X** [comment]
@pokedo0 good to hear! You're welcome.
I'm closing the issue then.
