### ISSUE TITLE
FFmpeg super slow - probably not using nvenc - how to fix?

### ISSUE THREAD

**Issue by GalGreenfield** [k4yt3x/video2x#605]
Hello, FFmpeg is being super slow - I can upscale a 4GB 1080p file to 4K in about 30 minutes, with the file stitching by FFmpeg not being completeld even after a few hours. It's probably not using nvenc - how can I fix it?

**Comment by k4yt3x** [comment]
I'll suggest you to not use NVENC since H.264 will give you better quality with the same bitrate. FFmpeg shouldn't take that long to process the frames. Are there any error logs or anything or is it just hanging there? Do you observe any CPU usages by FFmpeg?

**Comment by GalGreenfield** [comment]
I think I'm not using nvenc, and still FFmpeg doesn't even finish building the video file after hours of running, and IIRC I also get eventually some error failure shout it.

Here's a detailed post I wrote in Anime4KCPP's repo's issues

**Comment by k4yt3x** [comment]
It will be helpful if you have the error log, but in the past few reports of this same problem nobody was able to provide the error log since FFmpeg just hangs. I don't have the dev environment to debug the old 4.8.1 version either.

v2x was completely redesigned in 5.0.0 and this problem shouldn't exist in 5.0.0. The issue here is that it only supports command line so far as I haven't written a GUI for it. I also haven't added Anime4K support for it yet since the newest A4K is written in GLSL or C++ if I want to use Anime4KCPP. I'll need to figure out how to write a Python FFI for those two libraries to be able to use them.

With that said, 5.0.0 does run quite well with waifu2x, SRMD, RealSR, and RIFE. If you feel comfortable playing with command line stuff, maybe try [v2x on Colab](https://colab.research.google.com/drive/1gWEwcA9y57EsxwOjmLNmNMXPsafw0kGo) or [the container image](https://github.com/k4yt3x/video2x/pkgs/container/video2x)
