### ISSUE TITLE
Ultra slow Upscaling

### ISSUE THREAD

**Issue by Keerigan45** [k4yt3x/video2x#638]
Hey, i'm upscaling an IRL Video with the RealSR Model and i'm only doing 0.01 images per seconds with a 2070 is it normal ?

**Comment by k4yt3x** [comment]
Sounds about right, my A6000 only does 0.18 or something like that. Open your task manager and make sure you see CUDA usage, then it's what it should be.

**Comment by Keerigan45** [comment]
Okay, and do you know if it's worth it to take a Colab pro+ ?

**Comment by k4yt3x** [comment]
I'm not sure how much it means to you to be able to run upscales, and I'm not sure how much money you have, so the only recommendation I can give you at this point is to try Colab free first and tell you that Colab Pro/Pro+'s A100 gives you approximately the speed of a 2080Ti (I tested it because I a 2080Ti).

**Comment by k4yt3x** [comment]
Also, the [standard test clip](https://github.com/k4yt3x/video2x#standard-test-clip) runs at about 1 FPS on my 2080 Ti. You can use it as a reference. I expect a 2070 to be able to do at least 0.5. If it's lower than that please let me know, it may signal that there is a problem with your environment.
