### ISSUE TITLE
support realesrgan & restore lite version

### ISSUE THREAD

**Issue by alighamdan** [k4yt3x/video2x#643]
can you support [realesrgan](https://github.com/xinntao/Real-ESRGAN) in video2x and restore the lite version?

lite version can be helpful for peoples who doesn't have good wifi to install the full version '1>gb'?

**Comment by k4yt3x** [comment]
> can you support [realesrgan](https://github.com/xinntao/Real-ESRGAN) in video2x

Real ESRGAN support is already on the way, but I'm having a hard time writing the code to find the correct model since their naming scheme is nothing short of chaotic.

>  and restore the lite version?

I think you've mistaken what the lite version is. The full version contains all the dependencies necessary for running the program. The lite version downloads only the main executable plus a setup script, but that setup script still has to be run and download all the components for the program to run properly. It's really just "download them altogether" vs. "download them yourself" -- you'll still need to download that much either way. I removed lite only because the setup script was broken by upstream changes.

**Comment by k4yt3x** [comment]
Also, what I said about the lite version is only for 4.8.x. Version 5.0.0 now follows a different design path, and has a true [slim version for the containers](https://github.com/k4yt3x/video2x/pkgs/container/video2x/18100598?tag=5.0.0-beta5-slim-alpine) which only works for AMD and doesn't contain the bulky CUDA files for NVIDIA GPUs.

**Comment by redthing1** [comment]
Any update on realesrgan?

**Comment by tomika** [comment]
I also would appreciate Real-ESRGAN support, because I would like to use this converting live scenes instead of animes. I just post here to get notification on update, sorry.
