### ISSUE TITLE
Feature: pause work

### ISSUE THREAD

**Issue by AlvaroBeiro** [k4yt3x/video2x#65]
I'm trying to convert a 20 minute video from 576p to 1080p. I'm using cuda and it says it will take 14 hours. I don't like to have my computer working at 100% for such a long time, that's why I would like to have some kind of pause/resume. It could work just by pausing the script or by comparing two folders and seeing where it stopped upscaling, and restarting from there.

**Comment by K4YT3X** [comment]
waifu2x controls the upscaling process, so video2x can't really interviene with the upscaling process.
Something major has to be changed in order for this to be possible.

**Comment by dtgraham9** [comment]
completed_command = subprocess.run(execute, check=True)
completed_command = subprocess.Popen(execute, check=True)
With p=psutil.Process(completed_command) it may be possible to halt the thread's execution with p.suspend() and followed up with p.resume().  
Otherwise waifu2x's may allow for popen.communicate() and may have functions ready to handle a pause.

**Comment by K4YT3X** [comment]
> What Alvaro Beiro is describing to me sounds like quitting the program and resuming from a save state.

That's what I was thinking as well, but it sounds pretty hard to implement.
If it's simply pause and resume without exiting, then I think it's more viable.

**Comment by rasm685p** [comment]
You should be able to create something simple as a txt file with "1172/123212 frames progressed" 
If you load the txt file then it will just continue with 1173?

**Comment by k4yt3x** [comment]
> You should be able to create something simple as a txt file with "1172/123212 frames progressed"
> If you load the txt file then it will just continue with 1173?

`Video2X` does not control the progress,`waifu2x` does. Yes, video2x can count how many frames have been upscaled, but now I need to find out how to make waifu2x stop its job gracefully and such.

**Comment by dtgraham9** [comment]
k4yt3x from my understanding of your code you pass the entire temp frame directory to waifu2x, right?
If that's the case rasm685p, there is so code aside to send individual files/ smaller broken up temp directories.  

If the code was reworked to send individual frames to be upscaled by wiafu2x instead of an entire directory, yes it could be possible to create a txt file with start frame number, but no system is in place for that.  I would like to work on that, but my hands are tied up with work.  As summer approaches I should be able to contribute to this repo.  

The other option is see if waifu2x is open to receive stdin signals, and how it handles them.  Unfortunately, I don't have the time to see if waifu2x has this functionality built into it.   

If anything I said was wrong about your code k4yt3x please feel free to reply and correct me.  I went through most of your code in a few hours and got a rough overview of the systems.

**Comment by k4yt3x** [comment]
@dtgraham9 as mentioned in #11, processing individual frames greatly reduce the efficiency of upscaling.
I'm curious to see if I can stop waifu2x gracefully, but unfortunately that has to happen after my exam weeks.

**Comment by dtgraham9** [comment]
@k4yt3x I'll put some time into looking into it as well when I get time too, good luck on exams.  Mine aren't for a while.  My C++ skills are quite rusty.

**Comment by k4yt3x** [comment]
@dtgraham9 you have my appreciation. Thanks for helping out.
waifu2x-converter-cpp developers are quite engaging in issues opened, and are actively making changes and improvements. If we do need something specific, I think they might be happy to help.

Wish the exams are over quicker so I can work on my own stuff.

**Comment by k4yt3x** [comment]
On this topic, I was able to simply pause and resume the waifu2x process from `resmon`.
That's some progress I guess.

![image](https://user-images.githubusercontent.com/21986859/56871187-2d9b6a80-69e8-11e9-9552-b4ae5da24b51.png)

**Comment by DJPlaya** [comment]
@k4yt3x 
You may want to take a look at the CMD Tools Systeminternals, the PS Tools Collection may has something you could implement simply by doing a cmd call.
This for Example should do the Job > https://docs.microsoft.com/en-us/sysinternals/downloads/pssuspend
Otherwise you could also set the Priority of the Process to "Idle" which would end in a similar Result.

**Comment by k4yt3x** [comment]
@DJPlaya thanks for the suggestions. I would like to be able to use python to do a native API call, or use a C library to call the Windows API, instead of executing a shell command. If all of that don't work out, maybe I can then consider cmd calls.

**Comment by hart0** [comment]
I tried pausing and resuming (both the waifu2x and python processes since python continued to use significant CPU usage with waifu2x being paused) and when I tried to resume it ended up crashing and deleting all of the images/folders in the temp folder. I assumed if anything would happen I could just restart the waifu2x-caffe process using the same input/output paths.

Unfortunate because I was 48 hours into a week long conversion.

**Comment by deton24** [comment]
Didn't read the thread, but the app and/or dependent processes should be able to be suspended by Process Explorer. Maybe just mark all of them together and via RBM press suspend.

**Comment by k4yt3x** [comment]
@tamodolo Dandere2x is using the approach you described, but I'm trying to consider a different approach that doesn't require chunking. I want the upscaling to stop when I click stop.

I'm already working on that, but it's more complicated than that. I want a zip bundle to be created when the upscaling stops.

**Comment by tamodolo** [comment]
I didn't know dandere2x has that as it don't work here for some reason.

It's just a sugestion but the method I sugested seems easy enough to implement as I see some of the behaviors necessary already there and it's good enough to solve the problem for now. Your method could be implemented without hury then as it's complicated.

**Comment by Xyz00777** [comment]
it would be nice if we had 2 pause buttons.
1 for pause the actuall process (that what you are at looking atm how to do it)
2 to pause the quarry (what you could already implement? because you dont have to pause the actual upsampling)

**Comment by codomposer** [comment]
@k4yt3x Could you let me know how can I use this video2x to get the best quality result for video x4 upscaling?
Which model should I use?
The input video is a short time natural video

**Comment by k4yt3x** [comment]
@codomposer Either ask in the Telegram group or open a new issue. You're commenting on an ancient thread.
