### ISSUE TITLE
Where is the path of the config file (yaml or json) on Ubuntu?

### ISSUE THREAD

**Issue by chirun09** [k4yt3x/video2x#652]
I could not find the path in the documentation page

**Comment by k4yt3x** [comment]
Which version are you using?

**Comment by chirun09** [comment]
5.0.0-beta5

**Comment by k4yt3x** [comment]
5.0.0 doesn't have a config file anymore. There might be one in future betas for customizing FFmpeg params, but there isn't any for now. Everything's specified through CLI args.

**Comment by chirun09** [comment]
how to specify ffmpeg parameter in cli?

**Comment by k4yt3x** [comment]
Right now you can't, which is why it needs to be changed later. It defaults to libx264, CFR=17, pixel format=yuv420p. This section of the code is where it's defined.

https://github.com/k4yt3x/video2x/blob/d23613113454f3699ce5cd6e48a850f20f11cc79/video2x/encoder.py#L106-L129

The inability to edit this is why we've talked about this in our discussion group to add a config to make it customizable, but that'll have to happen after some other issues we're encountering right now are resolved.

**Comment by k4yt3x** [comment]
If you really need to customize this, either run it from source code or use 4.8.1.
