### ISSUE TITLE
Try to open video2x_gui but always closing again within a second

### ISSUE THREAD

**Issue by Lenardeus** [k4yt3x/video2x#699]
I try to join the telegram but got kicked even before typing anything, I can show the vids as well

Tried to open the .exe the prompt comes out but always closed again within a second i cant even take a picture 

already installed latest Java jdk 12, MC visual c++ 2019, is there any other program or anything i should now to open this program? cheers

**Comment by k4yt3x** [comment]
> I try to join the telegram but got kicked even before typing anything

We don't have any kind of mechanism that will do this. It might be Telegram doing it automatically due to the phone number you used to register the account. I know there are restrictions on Iranian and Chinese phone numbers. Give me your account username and I can invite you manually.

> already installed latest Java jdk 12, MC visual c++ 2019...

This is a Python program, and a Python runtime has already been bundled within the exe file, so you shouldn't need to install anything extra, in theory.

> Tried to open the .exe the prompt comes out but always closed again within a second

If you want the GUI, run `video2x_gui.exe`, not `video2x.exe`.
