### ISSUE TITLE
Google Colab Runtime Crashing

### ISSUE THREAD

**Issue by liston611** [k4yt3x/video2x#778]
When using Video2x in Google Colab via the posted template, runtime crashes.

-I've followed all instructions, including restarting runtime
-I was initially trying on a large file (~22,000 frames, 1080p -> 1440p), but also tried with a very small file (~450 frames, 240p -> 480p). Large file crashed every time around the 8 minute mark, about 2%. Small file crashed after 6 seconds, or 19%.

Log from small file is attached.
[small.log](https://github.com/k4yt3x/video2x/files/10015020/small.log)
[large.log](https://github.com/k4yt3x/video2x/files/10015021/large.log)

**Comment by kialos-b** [comment]
Same problem here on Colab. Trying to upscale a 5 minute video from 240p to 720p, runtime crashes exactly after 33 seconds. Tried 5 instances with the same source video, all 5 crash at 33 second. Maybe the error is on the Google Drive side? Since I noticed it always crashes after "Executing: Cell>Upscale()>write()" at the bottom of the screen
