### ISSUE TITLE
[Error] An exception has occurred

### ISSUE THREAD

**Issue by Mario-119** [k4yt3x/video2x#79]
While up-scaling a video, everything runs fine until it hits 33% or so. The error pasted below comes up, and all progress halts. This has happened 2 times in a row, so it doesn't seem to be a one off problem. I read that some people were experiencing similar issues, but none of the fixes listed have worked for me.   
```
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 306, in <module>
  File "upscaler.py", line 293, in run
  File "upscaler.py", line 232, in _upscale_frames
  File "waifu2x_caffe.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Alex\\Downloads\\video2x-2.7.0-win32-full\\video2x-2.7.0-win32-full\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_width', '3840', '--scale_height', '2160', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\Alex\\AppData\\Local\\Temp\\video2x\\tmpkqvvjwhw\\2', '--output_path', 'C:\\Users\\Alex\\AppData\\Local\\Temp\\video2x\\tmpjchrdkry']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using
```

**Comment by k4yt3x** [comment]
This error message doesn't tell all the problems.
Include more logs and preferably screenshots if possible.

**Comment by metzo007** [comment]
I did try Video2X 2.7.0 today and got the same error message

!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 306, in <module>
  File "upscaler.py", line 293, in run
  File "upscaler.py", line 232, in _upscale_frames
  File "waifu2x_caffe.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\video2x\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_width', '1920', '--scale_height', '1080', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmpev7h35gr\\0', '--output_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmpah8bnei3', '--model_dir', 'C:\\video2x\\dependencies\\waifu2x-caffe\\models\\photo']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using

old versions of video2x work fine

**Comment by k4yt3x** [comment]
Did you try 2.7.1?

**Comment by jitsuCM** [comment]
Same issue on 2.7.1. I Managed to track this down a bit. Running video2x like this:

`(video2x) D:\video2x>python video2x.py -i 1.mp4 -o 2.mp4 -y upresnet10 -t 3 -r 1.5 -m cudnn`

Gives the already known error message:
`Upscaling Progress:   0%|                              | 0/596 [00:01<?, ?it/s][!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 318, in <module>
    upscaler.run()
  File "D:\video2x\upscaler.py", line 295, in run
    self._upscale_frames(w2)
  File "D:\video2x\upscaler.py", line 234, in _upscale_frames
    raise(self.upscaler_exceptions[0])
  File "D:\video2x\waifu2x_caffe.py", line 83, in upscale
    completed_command = subprocess.run(execute, check=True)
  File "D:\Anaconda3\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\Michal\\AppData\\Local\\video2x\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '1.5', '--noise_level', '3', '--process', 'cudnn', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'P:/Temp/v2/tmpq_kfo5w_\\1', '--output_path', 'P:/Temp/v2/tmp_6rzu9ph', '--model_dir', 'upresnet10']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using`

NOTE1: Running this command through waifu2x-caffe-cui doesn't give much more information. Maybe it has a verbose switch to debug this, would have to see.
NOTE2: As I expected, changing the order of the arguments didn't change a thing. Changing the model also doesn't make it work.

To my suprise running this:
`(video2x) D:\video2x>python video2x.py -i 1.mp4 -o 2.mp4 -t 3 -r 1.5 -m cudnn`
works perfectly fine!
Notice how the only thing that got removed is the -y switch with upresnet10 model. Now it uses the default one.


Also, there seems to be something funky going with the argument parsing/passing in general, since FFMPEG prints out this for me:

`Trailing options were found on the commandline.`
`2019-04-21 09:30:05.340630 [+] INFO: Executing: ['C:\\Users\\...\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-i', 'D:\\video2x\\1.mp4', 'P:/Temp/v2/tmph9lzinek\\extracted_%0d.png', '-hwaccel', 'auto', '-y']`

I don't know the quirks, but that -y switch seems out of place :)

Either way, it's the waifu CUI that fails somehow. Running it without a model make things suddenly work.
I get the same results when running waifu directly, so it doesn't seem to be something Video2x related?

**Comment by k4yt3x** [comment]
One thing to point out, the `-y/--model_dir` argument should not just specify the name of the model, but the actual path to the folder that contains the model JSON files.

**Comment by jitsuCM** [comment]
That is one valuable info. Will try that today.

**Comment by k4yt3x** [comment]
No response from issue owner.
