### ISSUE TITLE
ZeroDivisionError?

### ISSUE THREAD

**Issue by YachtSail** [K4YT3X/video2x#8]
After the program finished processing all the frames, the following message appeared:
video:4418846kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 215, in <module>
    video2x()
  File "video2x.py", line 150, in video2x
    framerate = float(Fraction(info['streams'][0]['avg_frame_rate']))
  File "C:\Python27\lib\fractions.py", line 162, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)

What could have caused this problem? Does this program require certain video coding format to run properly?

**Comment by kwsou** [comment]
Just experienced this exact issue a moment ago. The problem lies in trying to obtain the framerate of the video from an non-video stream.

I figure for most of the time, the videos being used have the video stream before the audio stream, so the hardcoded `info['streams'][0]` will work but if the audio stream is first, it will use the information in that stream, which will have a framerate of 0/0.

Older versions of this program would probably also experience this same error when they attempt to obtain the width/height from the first stream index as well.

This implementation does not also account for the case where you have multiple video streams inside the file.

The workaround I used for now was to change the stream index to 1 since my file had the video stream at that index instead. You could also just hardcode the framerate variable to a specific value. Not a real fix, but it's enough to get it working until this issue is resolved.

**Comment by K4YT3X** [comment]
@YachtSail thanks for the issue. Will take a look ASAP.

**Comment by K4YT3X** [comment]
@YachtSail 
I looked at the error and saw this line:
> File "C:\Python27\lib\fractions.py", line 162, in new

This software runs with Python3 which is declared in its shebang, where python2 is used in your case.
`python` command in the documentation doesn't define the version of Python, the code does.

To avoid confusion I might change the documentation too. Try using python3 first and see if the issue remains.

**Comment by YachtSail** [comment]
Here is the error report:
[!] ERROR: An exception occurred
Traceback (most recent call last):
  File "video2x.py", line 215, in <module>
    video2x()
  File "video2x.py", line 150, in video2x
    framerate = float(Fraction(info['streams'][0]['avg_frame_rate']))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\fractions.py", line 178, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)
I have previously installed two versions of python. For this test, I uninstalled them all and reinstalled python 3 just to make sure everything works. It seems that the program ran in python 3 this time, but the ZeroDivisionError issue persists.

**Comment by K4YT3X** [comment]
@YachtSail Roger that. Thanks to @kwsou 's comment which I read carefully, I will look into the problem and see if I can get a quick fix.

Sorry but you might have to stick to @kwsou 's fix for the moment.

**Comment by K4YT3X** [comment]
@YachtSail @kwsou I will try to change from ffmpeg to ffmpeg-python and see if that will solve the problem. It should be a more elegant solution that just executing stuff from the commandline.

**Comment by verbiate** [comment]
Seeing the error again on version 2.10.0:

`[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 431, in <module>
    upscaler.run()
  File "E:\upscale\video2x-2.9.0-win32-full\video2x-master-batchfix\bin\upscaler.py", line 334, in run
    framerate = float(Fraction(video_info['streams'][video_stream_index]['avg_frame_rate']))
  File "C:\Program Files\Python37\lib\fractions.py", line 178, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(0, 0)`

Interestingly, the line before says it's calling \bin\ffprobe.exe, but I'm running the Python scripts directly and that executable isn't located in \bin

**Comment by k4yt3x** [comment]
`/bin/ffprobe.exe`? That sounds so *nix.
Try the newest version (2.10.0) instead of the release. The exe release isn't as up-to-date as the python source code. I might automate this packaging later using GitHub Actions so the exe is up to date. However, for now, I recommend you to try the python version as it fixed some problems in 2.9.0.

**Comment by verbiate** [comment]
As I mentioned, I am running 2.10.0, not 2.9.0.

**Comment by k4yt3x** [comment]
@verbiate ok got it.
Could you please open a new issue for this error?
