### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by DataSciCode** [k4yt3x/video2x#833]
[video2x_error.log](https://github.com/k4yt3x/video2x/files/10614006/video2x_error.log)

**Comment by Cracko298** [comment]
I've had this happen to me as well. I found out it happens when the video(s) you have selected are a .wmv file(s). As the log suggests it's trying to calculate the frames of your .wmv video file and fails. You'll need to convert it to a .mp4 file via an Online converter such as "Cloud Convert" or an application, such as " Any Video Converter". Just convert it to an .mp4 (h265 codec).

Note: I am not apart or affiliated with Video2X in anyway. Just thought this would help you.
