### ISSUE TITLE
AMD GPU Requirements

### ISSUE THREAD

**Issue by snowhunter** [k4yt3x/video2x#886]
I'm running the Docker image, on a Linux host with an AMD GPU, but am unable to have this run without errors.

The documentation says:

> Make sure your host has the proper GPU and Vulkan libraries and drivers,

What exactly is it looking for? When I use the command provided I just see the following repeated:

> vkEnumeratePhysicalDevices failed -3

Running vulkaninfo on the host shows that Vulkan is supported, so I'm assuming that I'm missing a dependency or perhaps not passing it to the container correctly.

**Comment by cufbas** [comment]
Having the same issue here. Did you find a solution @snowhunter ?

**Comment by snowhunter** [comment]
No, and based upon the previous threads it's going to be something along the lines of "wrong driver version" and it will be trial and error to figure out what would match.

It would be good if someone was able to confirm that it worked for them and which kernel/distro version they used so that I can switch it up.

I tried with Fedora 37. I'll upgrade to 38 this weekend and see whether that helps. Otherwise I'll start making boot USBs and test different distros and versions.

**Comment by pfmacedo** [comment]
Adding this to the correct issue now..

IMO the problem is likely the base image - looking at the docker file, it uses an Nvidia-provided image as the base (docker.io/nvidia/vulkan:1.3-470 ), which was last updated over two years ago and is based on an old Ubuntu release. A possible solution would be to change the Docker file to run a full dist upgrade to the current Ubuntu stable as one of the first steps and that might fix the issue; alternatively, using a separate base image built on latest ubuntu/debian, but that would mean extra steps to add the Nvidia-provided bits on top.
