### ISSUE TITLE
Command '['C:\\Users\\cmrag\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan', '-n', '2', '-s', '2', '-t', '400', '-m', 'C:\\Users\\cmrag\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\waifu2x-ncnn-vulkan\\models-cunet', '-g', '0', '-j', '6:6:6', '-f', 'png', '-i', 'C:\\Users\\cmrag\\AppData\\Local\\Temp\\video2x\\tmpdcuglf77', '-o', 'C:\\Users\\cmrag\\AppData\\Local\\Temp\\video2x\\tmpd02j1prs']' returned non-zero exit status 3221225781.

### ISSUE THREAD

**Issue by DevOpsRagu** [k4yt3x/video2x#980]
Hi,

I was tying to upscale my video which was around 300 MB in MP4 format. After running for close to 4 hours it gave an error

Attached the log file here. Please help.

[video2x_error_Noise3.log](https://github.com/k4yt3x/video2x/files/12659008/video2x_error_Noise3.log)

**Comment by DevOpsRagu** [comment]
Please let me know the fix for this

**Comment by k4yt3x** [comment]
I had to close a bunch of issues since they're mostly duplicate of each other. In your case you're getting the error due to

> Unable to delete: C:\Users\cmrag\AppData\Local\Temp\video2x

I don't think you changed the permission to the directory manually, then it's some weird Windows permission error or interference from antivirus or some other program.

Either try changing the cache directory (read the warning on the release page) or turn off whatever that may be interfering with it. Or just use Colab.
